### ISSUE TITLE
 inaccessibilité panel administration

### ISSUE THREAD

**Issue by BryanEdeline** [Raphael-Lemaire/Shopbase#1]
Bonjour quand je souhaite accéder dans la partie admin en mettant le mot de passe il me donne une erreur. Qui m'empêche d'aller dans la partie admin de l'application web .
J'aimerais que l'erreur soit corrigée afin de pouvoir avoir accès au panel administration.
Je vous souhaite une bonne journée .
Cordialement.

Bryan Edeline

**Comment by Raphael-Lemaire** [comment]
Bonjour Bryan Edeline,

Après vérification de votre problème et du code de connexion vers le panel admin, il manquait la redirection vers le panel après vérification des identifiants. Après correction et ajout de la redirection, le problème est maintenant résolu. Désolé pour le désagrément et merci de nous avoir signalé cette erreur.
